import Head from "next/head";
import React from "react";
import { useQueryClient } from "react-query";
import { useSession } from "next-auth/react";
import { useDispatch, useSelector } from "react-redux";
import Form from "../components/Users/Form";
import Layout from "../components/Layout";
import Table from "../components/Users/Table";
import { deleteAction, toggleChangeAction } from "../redux/reducer";
import { deleteUser, getUsers } from "../utils/API";
import styles from "../styles/Users.module.css";

const Users = () => {
  const { data: session } = useSession();
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const dispatch = useDispatch();
  const queryClient = useQueryClient();
  const handleAdd = () => {
    // setVisible(!visible);
    dispatch(toggleChangeAction());
  };

  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryClient.prefetchQuery("users", getUsers);
      await dispatch(deleteAction(null));
    }
  };

  const canclehandler = async () => {
    await dispatch(deleteAction(null));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {session?.user && (
          <Layout title="HomePage">
            <div>
              <h1 className={styles.titleUsers}>
                These users are registered in Arrimo app!
              </h1>
              <div>
                <button onClick={handleAdd} className={styles.btnAddUser}>
                  Add New User
                </button>
              </div>
              {deleteId && DeleteComponent({ deletehandler, canclehandler })}
            </div>

            {visible && <Form />}

            <Table />
          </Layout>
        )}
      </main>
    </>
  );
};

export default Users;

function DeleteComponent({ deletehandler, canclehandler }) {
  return (
    <div className={styles.deleteContainer}>
      <p className={styles.deleteText}>Are you sure?</p>
      <button
        onClick={deletehandler}
        className={`${styles.confirmBtn} ${styles.confirm}`}
      >
        Yes
      </button>
      <button
        onClick={canclehandler}
        className={`${styles.confirmBtn} ${styles.reject}`}
      >
        No
      </button>
    </div>
  );
}
